// AUTO-GENERATED by web/scripts/build-glossary.mjs from docs/design/COPY.md. Do not edit by hand.
// Edit COPY.md, then run `node web/scripts/build-glossary.mjs`. glossary.sync.test.ts fails when this is stale.
import type { CopyData } from './copyTypes';

export const COPY_DATA: CopyData = {
  "glossary": [
    {
      "id": "stock",
      "group": "basics",
      "label": "Share of a company",
      "term": "shares of stock",
      "whatItIs": "A stock is a small piece of ownership in a company, sold as shares that people can buy and sell.",
      "whyItMatters": "When the business does well, its shares usually become worth more, and when it struggles, they usually lose value.",
      "usuallyGoodWhen": "the business behind the stock is healthy, but even strong companies can have falling prices for a while.",
      "related": [
        "price",
        "marketCap",
        "sector",
        "ticker"
      ]
    },
    {
      "id": "price",
      "group": "basics",
      "label": "Share price",
      "term": "last price",
      "whatItIs": "The latest price of one share, set by the market and updated every tick.",
      "whyItMatters": "It is about what you pay for each share if you buy now, or get if you sell, before fees and price impact.",
      "usuallyGoodWhen": "profits grow along with the price, but a low share price does not make a stock a bargain.",
      "related": [
        "peRatio",
        "marketCap",
        "tick",
        "priceImpact"
      ]
    },
    {
      "id": "marketCap",
      "group": "basics",
      "label": "Company size",
      "term": "market cap",
      "whatItIs": "The value of all of a company's shares added together: the share price times the number of shares.",
      "whyItMatters": "Size puts other numbers in context: bigger companies usually have bigger sales and profits, so compare margins and growth too.",
      "usuallyGoodWhen": "its size is backed by real profits, but being big does not protect a company from falling prices.",
      "related": [
        "price",
        "sharesOutstanding",
        "peRatio",
        "psRatio"
      ]
    },
    {
      "id": "sector",
      "group": "basics",
      "label": "Industry group",
      "term": "market sector",
      "whatItIs": "A group of companies that do similar work, such as shipping or banking.",
      "whyItMatters": "Comparing a company with others in its sector is fairer, because normal numbers differ a lot from one industry to another.",
      "usuallyGoodWhen": "a company's numbers hold up well against its own sector, but a whole sector can rise or fall together.",
      "related": [
        "index",
        "industryGrowth",
        "diversification"
      ]
    },
    {
      "id": "index",
      "group": "basics",
      "label": "Market tracker",
      "term": "market index",
      "whatItIs": "One number that tracks the prices of many companies at once, like the Pirate Composite for the whole market.",
      "whyItMatters": "It shows whether most prices are rising or falling, so you can tell if a move is about one company or everyone.",
      "usuallyGoodWhen": "your account keeps pace with the index over time, but beating it for a short stretch can be pure luck.",
      "related": [
        "sector",
        "beta",
        "breadth"
      ]
    },
    {
      "id": "volume",
      "group": "basics",
      "label": "Shares traded this session",
      "term": "trading volume",
      "whatItIs": "The number of shares that crews traded during the current session.",
      "whyItMatters": "A jump in volume shows which companies crews are busy trading, which often follows news.",
      "usuallyGoodWhen": "you check the news behind a volume jump, but price moves caused by heavy crew trading fade over time.",
      "related": [
        "news",
        "session",
        "sessionChange"
      ]
    },
    {
      "id": "beta",
      "group": "basics",
      "label": "Swings vs. the market",
      "term": "market beta",
      "whatItIs": "A number that shows how much a stock tends to move when the whole market moves; 1.0 means about the same amount.",
      "whyItMatters": "A beta above 1 means the stock tends to move more than the market when the market moves, up or down; below 1 means less.",
      "usuallyGoodWhen": "it matches how many ups and downs you can handle, but a low beta does not protect against company news.",
      "related": [
        "index",
        "diversification",
        "news"
      ]
    },
    {
      "id": "analystRating",
      "group": "basics",
      "label": "Analyst view",
      "term": "analyst rating",
      "whatItIs": "The opinion of the game's analysts, from Strong Buy to Strong Sell, about where they think the price is heading.",
      "whyItMatters": "It is a second opinion to weigh against your own research, but analysts in this game are often wrong.",
      "usuallyGoodWhen": "the analyst view agrees with what the company's numbers show, but analysts give a hint, not a promise.",
      "related": [
        "priceTarget",
        "news",
        "peRatio"
      ]
    },
    {
      "id": "priceTarget",
      "group": "basics",
      "label": "Analyst price guess",
      "term": "price target",
      "whatItIs": "The price analysts expect the stock to reach over the next year; in this game, one full game counts as a year.",
      "whyItMatters": "The gap between the target and the current price shows how much analysts think the price could rise or fall.",
      "usuallyGoodWhen": "the target is further above the price than for similar companies, but targets here usually run high.",
      "related": [
        "analystRating",
        "price"
      ]
    },
    {
      "id": "voyageRange",
      "group": "basics",
      "label": "Game high and low",
      "term": "game range",
      "whatItIs": "The highest and lowest prices the stock has reached since this game began.",
      "whyItMatters": "It shows whether the current price is near the top or the bottom of its path so far.",
      "usuallyGoodWhen": "the price holds near the high because the business keeps improving, but prices near a high can also drop back.",
      "related": [
        "week52Range",
        "sessionRange",
        "voyageChange"
      ]
    },
    {
      "id": "sessionChange",
      "group": "basics",
      "label": "Change this session",
      "term": "session change",
      "whatItIs": "How much a price or your account value has changed since the current session began, in doubloons and as a percent.",
      "whyItMatters": "It shows the short-term move, which is often driven by news or random swings rather than the business itself.",
      "usuallyGoodWhen": "a rise follows real news about the business, but one session is a short time and moves often reverse.",
      "related": [
        "session",
        "voyageChange",
        "totalGain"
      ]
    },
    {
      "id": "revenue",
      "group": "profit",
      "label": "Yearly sales",
      "term": "annual revenue",
      "whatItIs": "All the money a company brought in from customers last year, before paying any costs.",
      "whyItMatters": "Sales are where profit starts: a company cannot keep making money for long without steady or growing sales.",
      "usuallyGoodWhen": "sales rise year after year, but sales mean little if costs rise even faster.",
      "related": [
        "revenueGrowth",
        "netIncome",
        "netMargin",
        "psRatio"
      ]
    },
    {
      "id": "netIncome",
      "group": "profit",
      "label": "Yearly profit",
      "term": "net income",
      "whatItIs": "The money left from sales after paying every cost, including interest and taxes, for the most recent year.",
      "whyItMatters": "Profit is what a company earns for its owners, and over time it drives how much the business is worth.",
      "usuallyGoodWhen": "profit is positive and growing, but one big year can come from a one-time event that will not repeat.",
      "related": [
        "revenue",
        "netMargin",
        "eps",
        "peRatio"
      ]
    },
    {
      "id": "netMargin",
      "group": "profit",
      "label": "Profit margin",
      "term": "net margin",
      "whatItIs": "The share of sales left as profit after all costs, shown as a percent.",
      "whyItMatters": "It shows how well a company turns sales into profit: a 14% margin means 14 of every 100 doubloons of sales is profit.",
      "usuallyGoodWhen": "the margin is steady or rising, but some industries always keep less profit from sales, so compare within the sector.",
      "related": [
        "netIncome",
        "grossMargin",
        "operatingMargin",
        "revenue"
      ]
    },
    {
      "id": "grossMargin",
      "group": "profit",
      "label": "Sales kept after direct costs",
      "term": "gross margin",
      "whatItIs": "The share of sales left after paying the direct costs of what it sells, before rent, office staff, marketing and other running costs.",
      "whyItMatters": "A high gross margin leaves more room to pay every other cost and still make a profit.",
      "usuallyGoodWhen": "it holds steady over the years, but large other costs can still leave a loss.",
      "related": [
        "grossProfit",
        "costOfRevenue",
        "operatingMargin",
        "netMargin"
      ]
    },
    {
      "id": "operatingMargin",
      "group": "profit",
      "label": "Sales kept after running costs",
      "term": "operating margin",
      "whatItIs": "The share of sales left after paying direct costs and the everyday costs of running the business, before interest and taxes.",
      "whyItMatters": "It shows how well the main business makes money, without the effects of loans or taxes.",
      "usuallyGoodWhen": "it is steady or rising over time, but interest on big loans can still eat much of this profit.",
      "related": [
        "operatingIncome",
        "grossMargin",
        "netMargin",
        "ebitda"
      ]
    },
    {
      "id": "eps",
      "group": "profit",
      "label": "Profit per share",
      "term": "earnings per share",
      "whatItIs": "EPS, short for earnings per share, is yearly profit divided by the number of shares. Earnings is another word for profit.",
      "whyItMatters": "It tells you how much profit stands behind each share, and it is used to work out price vs. profit (P/E).",
      "usuallyGoodWhen": "it grows year after year, but EPS alone cannot compare companies, because each has a different number of shares.",
      "related": [
        "netIncome",
        "peRatio",
        "sharesOutstanding"
      ]
    },
    {
      "id": "roe",
      "group": "profit",
      "label": "Return on owner equity",
      "term": "return on equity",
      "whatItIs": "ROE, short for return on equity, is yearly profit as a percent of owner equity: what the company owns minus what it owes.",
      "whyItMatters": "It shows how hard the owners' money is working to produce profit.",
      "usuallyGoodWhen": "it is steady and above the sector average, but heavy borrowing can push it up while making the company riskier.",
      "related": [
        "equity",
        "roa",
        "debtToEquity",
        "netIncome"
      ]
    },
    {
      "id": "roa",
      "group": "profit",
      "label": "Profit from what it owns",
      "term": "return on assets",
      "whatItIs": "ROA, short for return on assets, is yearly profit as a percent of everything the company owns.",
      "whyItMatters": "It shows how well a company turns its buildings, equipment, cash and other things it owns into profit. Borrowing affects it less than return on equity.",
      "usuallyGoodWhen": "it is higher than similar companies, but businesses that need lots of equipment naturally have lower numbers.",
      "related": [
        "totalAssets",
        "roe",
        "netIncome"
      ]
    },
    {
      "id": "ebitda",
      "group": "profit",
      "label": "Core profit",
      "term": "earnings before interest, taxes, depreciation and amortization",
      "whatItIs": "EBITDA is profit before loan interest and taxes, and before subtracting the yearly cost of wear-and-tear on buildings, equipment and other long-lasting things.",
      "whyItMatters": "It lets you compare what the main business earns, even when companies have different loans or tax bills.",
      "usuallyGoodWhen": "it grows along with sales, but it leaves out real costs like interest and replacing worn-out equipment.",
      "related": [
        "evToEbitda",
        "operatingIncome",
        "operatingMargin"
      ]
    },
    {
      "id": "revenueGrowth",
      "group": "growth",
      "label": "Sales growth",
      "term": "revenue growth",
      "whatItIs": "The average yearly change in sales over the last 3 years, from the oldest of the 4 yearly reports to the newest.",
      "whyItMatters": "Growing sales can mean more customers and bigger profits later, while shrinking sales can signal trouble.",
      "usuallyGoodWhen": "sales grow faster than the sector average, but fast growth means little if the company keeps losing money.",
      "related": [
        "revenue",
        "industryGrowth",
        "tam",
        "netIncome"
      ]
    },
    {
      "id": "industryGrowth",
      "group": "growth",
      "label": "Industry growth",
      "term": "industry growth rate",
      "whatItIs": "How fast the whole industry is expected to grow each year, counting all the companies in it together.",
      "whyItMatters": "A growing industry can lift many companies at once, while a shrinking one makes growth harder for everyone.",
      "usuallyGoodWhen": "the industry is growing, but a company can still lose ground to rivals in a booming industry.",
      "related": [
        "sector",
        "tam",
        "revenueGrowth"
      ]
    },
    {
      "id": "tam",
      "group": "growth",
      "label": "Total market size",
      "term": "total addressable market",
      "whatItIs": "TAM, short for total addressable market, is the yearly sales possible if every customer in this market bought from one company.",
      "whyItMatters": "It shows how much room a company has to grow before it runs out of new customers.",
      "usuallyGoodWhen": "the market is much bigger than the company's sales, but a big market also attracts many rivals.",
      "related": [
        "industryGrowth",
        "revenue",
        "revenueGrowth"
      ]
    },
    {
      "id": "debtToEquity",
      "group": "debt",
      "label": "Debt vs. owner equity",
      "term": "debt-to-equity",
      "whatItIs": "Borrowed money compared with owner equity; 0.62 means 62 doubloons of debt for every 100 doubloons of owner equity.",
      "whyItMatters": "Debt must be paid back with interest, so a company with lots of debt has less room for mistakes when times get hard.",
      "usuallyGoodWhen": "it is at or below the sector average, but even a little debt can hurt if profits suddenly fall.",
      "related": [
        "totalDebt",
        "equity",
        "currentRatio",
        "roe"
      ]
    },
    {
      "id": "currentRatio",
      "group": "debt",
      "label": "Short-term bill coverage",
      "term": "current ratio",
      "whatItIs": "Cash and other things the company can turn into cash within a year, divided by the bills it must pay within a year.",
      "whyItMatters": "Above 1 means it has more short-term money than short-term bills, which makes those bills easier to pay on time.",
      "usuallyGoodWhen": "it is above 1, but a very high ratio can mean cash is sitting unused instead of growing the business.",
      "related": [
        "cash",
        "totalLiabilities",
        "debtToEquity"
      ]
    },
    {
      "id": "totalDebt",
      "group": "debt",
      "label": "Borrowed money",
      "term": "total debt",
      "whatItIs": "All the money the company has borrowed and still has to pay back, such as bank loans.",
      "whyItMatters": "Debt comes with interest payments that must be made in good times and bad.",
      "usuallyGoodWhen": "debt is small next to profit and cash, but a sudden sales drop can make any debt hard to pay.",
      "related": [
        "debtToEquity",
        "cash",
        "totalLiabilities",
        "evToEbitda"
      ]
    },
    {
      "id": "cash",
      "group": "debt",
      "label": "Cash on hand",
      "term": "cash and equivalents",
      "whatItIs": "The money the company has right now, ready to spend.",
      "whyItMatters": "Cash pays bills during hard times and lets a company act fast without borrowing.",
      "usuallyGoodWhen": "cash covers a good part of its debt, but a large pile of unused cash earns little for owners.",
      "related": [
        "totalDebt",
        "currentRatio",
        "freeCashFlow"
      ]
    },
    {
      "id": "equity",
      "group": "debt",
      "label": "Owner equity",
      "term": "shareholders' equity",
      "whatItIs": "What the company owns minus what it owes: the part of the business that belongs to its owners.",
      "whyItMatters": "Losses shrink it first, so it works like a safety cushion. It is also used in debt vs. owner equity, return on equity and price vs. owner equity.",
      "usuallyGoodWhen": "it grows over the years, but it comes from the company's records, so it can differ from company size.",
      "related": [
        "totalAssets",
        "totalLiabilities",
        "debtToEquity",
        "pbRatio",
        "roe"
      ]
    },
    {
      "id": "totalAssets",
      "group": "debt",
      "label": "Everything it owns",
      "term": "total assets",
      "whatItIs": "The value of everything the company owns, including cash, buildings, equipment and money customers still owe it.",
      "whyItMatters": "The things it owns are the tools it uses to make money, and they could be sold to pay what it owes.",
      "usuallyGoodWhen": "what it owns grows along with profit, but things bought with borrowed money also add debt.",
      "related": [
        "totalLiabilities",
        "equity",
        "roa"
      ]
    },
    {
      "id": "totalLiabilities",
      "group": "debt",
      "label": "Everything it owes",
      "term": "total liabilities",
      "whatItIs": "Everything the company owes to others, including loans, unpaid bills and other promises to pay.",
      "whyItMatters": "The less a company owes compared with what it owns, the more room it has when business slows down.",
      "usuallyGoodWhen": "it is well below what the company owns, but even small bills hurt if cash runs short.",
      "related": [
        "totalAssets",
        "totalDebt",
        "equity",
        "currentRatio"
      ]
    },
    {
      "id": "operatingCashFlow",
      "group": "profit",
      "label": "Cash from running the business",
      "term": "operating cash flow",
      "whatItIs": "The cash that actually came in from running the business last year, after paying everyday costs.",
      "whyItMatters": "Profit counts a sale even before the customer pays, so this shows whether profit is turning into real cash.",
      "usuallyGoodWhen": "it is at or above profit, but one strong year of cash can come from paying bills late.",
      "related": [
        "netIncome",
        "capex",
        "freeCashFlow"
      ]
    },
    {
      "id": "capex",
      "group": "growth",
      "label": "Spending on equipment and buildings",
      "term": "capital spending",
      "whatItIs": "Money spent on long-lasting things, like equipment and buildings, that the business will use for years.",
      "whyItMatters": "It keeps the business running and can build future growth, but it lowers the cash left over right now.",
      "usuallyGoodWhen": "the spending leads to growing sales over time, but heavy spending that never pays off drains cash.",
      "related": [
        "freeCashFlow",
        "operatingCashFlow",
        "revenueGrowth"
      ]
    },
    {
      "id": "freeCashFlow",
      "group": "profit",
      "label": "Cash left after investing",
      "term": "free cash flow",
      "whatItIs": "Cash from running the business minus spending on equipment and buildings: the money truly left over.",
      "whyItMatters": "Free cash can pay down debt, pay owners or fund growth without borrowing.",
      "usuallyGoodWhen": "it is positive and steady, but one strong year can come from cutting spending the business will need later.",
      "related": [
        "operatingCashFlow",
        "capex",
        "cash",
        "dividendYield"
      ]
    },
    {
      "id": "peRatio",
      "group": "value",
      "label": "Price vs. profit",
      "term": "P/E ratio",
      "whatItIs": "P/E, short for price-to-earnings, is the share price divided by yearly profit per share. Earnings is another word for profit.",
      "whyItMatters": "It shows what you pay for each Ð1 of profit, so you can compare prices fairly. A Ð50 share with Ð5 of profit per share has a P/E of 10.",
      "usuallyGoodWhen": "it is lower than similar companies, but a very low P/E can mean investors expect trouble.",
      "related": [
        "forwardPe",
        "eps",
        "psRatio",
        "evToEbitda"
      ]
    },
    {
      "id": "forwardPe",
      "group": "value",
      "label": "Price vs. next year's profit",
      "term": "forward P/E",
      "whatItIs": "The share price divided by the profit per share expected next year, instead of last year.",
      "whyItMatters": "If it is lower than the regular P/E, profit is expected to grow; if it is higher, profit is expected to shrink.",
      "usuallyGoodWhen": "it is below the regular P/E, but forecasts are guesses and often miss.",
      "related": [
        "peRatio",
        "eps",
        "analystRating"
      ]
    },
    {
      "id": "psRatio",
      "group": "value",
      "label": "Price vs. sales",
      "term": "P/S ratio",
      "whatItIs": "P/S, short for price-to-sales, is company size divided by yearly sales. A company worth Ð10 billion with Ð5 billion of sales has a P/S of 2.",
      "whyItMatters": "It still works when a company has no profit, so it helps compare companies that are losing money.",
      "usuallyGoodWhen": "it is lower than similar companies, but a low P/S can mean the company keeps little profit from sales.",
      "related": [
        "peRatio",
        "revenue",
        "netMargin",
        "marketCap"
      ]
    },
    {
      "id": "pbRatio",
      "group": "value",
      "label": "Price vs. owner equity",
      "term": "P/B ratio",
      "whatItIs": "P/B, short for price-to-book, is company size divided by owner equity: what it owns minus what it owes. Book means the company's own records.",
      "whyItMatters": "It shows how much investors pay compared with what the company's records say would be left for owners after paying all it owes.",
      "usuallyGoodWhen": "it is lower than similar companies, but companies that earn a lot while owning little naturally have a high P/B.",
      "related": [
        "equity",
        "peRatio",
        "roe"
      ]
    },
    {
      "id": "evToEbitda",
      "group": "value",
      "label": "Business price vs. core profit",
      "term": "EV/EBITDA",
      "whatItIs": "EV/EBITDA compares enterprise value (EV) with core profit (EBITDA). Enterprise value is company size plus debt minus cash; core profit is profit before interest, taxes and wear-and-tear.",
      "whyItMatters": "Because it counts debt, it compares prices fairly between companies that borrow a lot and companies that borrow little.",
      "usuallyGoodWhen": "it is lower than similar companies, but a low number can mean the business is expected to shrink.",
      "related": [
        "ebitda",
        "peRatio",
        "totalDebt",
        "cash"
      ]
    },
    {
      "id": "dividendYield",
      "group": "value",
      "label": "Yearly payout to owners",
      "term": "dividend yield",
      "whatItIs": "A dividend is cash a company pays its owners. The yield is one year of dividends as a percent of the share price.",
      "whyItMatters": "Steady payouts often come from steady profits; in this game they are shown for research and never added to your cash.",
      "usuallyGoodWhen": "payouts are steady, but companies can cut payouts, and a very high yield can mean the price fell.",
      "related": [
        "payoutRatio",
        "freeCashFlow",
        "netIncome"
      ]
    },
    {
      "id": "payoutRatio",
      "group": "value",
      "label": "Share of profit paid out",
      "term": "payout ratio",
      "whatItIs": "The percent of yearly profit that a company pays its owners in cash, called dividends.",
      "whyItMatters": "It shows how much profit is shared and how much is kept to grow the business or pay down debt.",
      "usuallyGoodWhen": "it is well below 100%, but a low payout alone does not show that the profit itself is healthy.",
      "related": [
        "dividendYield",
        "netIncome",
        "freeCashFlow"
      ]
    },
    {
      "id": "marketOrder",
      "group": "trading",
      "label": "Buy or sell now",
      "term": "market order",
      "whatItIs": "An order to buy or sell right away at about the current price, instead of waiting for a price you choose. Once the trade happens, it is filled.",
      "whyItMatters": "It is the only order type in this game, so the price you get depends on the moment you place it.",
      "usuallyGoodWhen": "you preview the estimate right before placing it, but the final price can still differ a little from the preview.",
      "related": [
        "price",
        "fee",
        "priceImpact",
        "tick"
      ]
    },
    {
      "id": "fee",
      "group": "trading",
      "label": "Trading fee",
      "term": "commission",
      "whatItIs": "A charge on every buy and every sell, set by the host as a percent of the order value (0.10% by default).",
      "whyItMatters": "Fees come out of your account win or lose, so trading back and forth adds up quickly.",
      "usuallyGoodWhen": "your expected gain is much larger than the fee, but the fee is charged even on losing trades.",
      "related": [
        "feesPaid",
        "marketOrder",
        "priceImpact"
      ]
    },
    {
      "id": "priceImpact",
      "group": "trading",
      "label": "Price nudge from your order",
      "term": "price impact",
      "whatItIs": "The way an order pushes the price against you, more for bigger orders: buying raises it a little, and selling lowers it a little.",
      "whyItMatters": "Big orders get a slightly worse price, and the nudge fades over time, so buying and quickly selling back usually loses money.",
      "usuallyGoodWhen": "your order is small compared with the company's share count, but every order moves the price a little.",
      "related": [
        "marketOrder",
        "fee",
        "intervalLimit",
        "sharesOutstanding"
      ]
    },
    {
      "id": "avgCost",
      "group": "trading",
      "label": "Average price paid",
      "term": "average cost",
      "whatItIs": "The average price per share across all your buys of one company, not counting fees.",
      "whyItMatters": "Comparing it with the current price shows whether your shares are up or down since you bought them.",
      "usuallyGoodWhen": "the price is above your average cost, but a paper gain can vanish if the price falls before you sell.",
      "related": [
        "costBasis",
        "unrealizedGain",
        "realizedGain"
      ]
    },
    {
      "id": "costBasis",
      "group": "trading",
      "label": "Total paid",
      "term": "cost basis",
      "whatItIs": "Your average price paid times the number of shares you own: what you paid for the shares you still hold.",
      "whyItMatters": "Your gain or loss on a holding is its current value minus its cost basis.",
      "usuallyGoodWhen": "the holding's value is above its cost basis, but that gain is not locked in until you sell.",
      "related": [
        "avgCost",
        "unrealizedGain",
        "totalGain"
      ]
    },
    {
      "id": "totalGain",
      "group": "trading",
      "label": "Total gain/loss",
      "term": "total return",
      "whatItIs": "How much you are up or down: account value minus starting cash, or for one holding, its value minus its cost basis.",
      "whyItMatters": "Every crew starts with the same cash, so the crew with the biggest total gain has the highest account value.",
      "usuallyGoodWhen": "it grows steadily over many sessions, but a gain can shrink fast if a big holding gets bad news.",
      "related": [
        "accountValue",
        "realizedGain",
        "unrealizedGain",
        "startingCash"
      ]
    },
    {
      "id": "realizedGain",
      "group": "trading",
      "label": "Locked-in gain/loss",
      "term": "realized gain",
      "whatItIs": "Profit or loss you locked in by selling: the sale amount, minus what those shares cost at your average price, minus the sale's fee.",
      "whyItMatters": "Once realized, the result is final, and later price moves cannot change it.",
      "usuallyGoodWhen": "you sell for more than your average cost, but fees on every sale can shrink small gains to almost nothing.",
      "related": [
        "unrealizedGain",
        "avgCost",
        "fee",
        "totalGain"
      ]
    },
    {
      "id": "unrealizedGain",
      "group": "trading",
      "label": "Paper gain/loss",
      "term": "unrealized gain",
      "whatItIs": "Profit or loss on shares you still own: their current value minus what you paid for them, not counting fees.",
      "whyItMatters": "It changes every tick with the price, and it only becomes final when you sell.",
      "usuallyGoodWhen": "it is positive, but a paper gain can disappear if the price drops before you sell.",
      "related": [
        "realizedGain",
        "costBasis",
        "avgCost"
      ]
    },
    {
      "id": "positionLimit",
      "group": "trading",
      "label": "Most in one company",
      "term": "position limit",
      "whatItIs": "A host rule that stops any buy from putting more than a set share of your account value into one company.",
      "whyItMatters": "It keeps any single company, lucky or unlucky, from deciding your whole game.",
      "usuallyGoodWhen": "your biggest holding stays well under the limit, but staying under the limit does not make a holding safe.",
      "related": [
        "diversification",
        "pctOfAccount",
        "intervalLimit"
      ]
    },
    {
      "id": "diversification",
      "group": "trading",
      "label": "Spreading your money",
      "term": "diversification",
      "whatItIs": "Owning several companies, ideally in different sectors, instead of putting all your money into one.",
      "whyItMatters": "When one company gets bad news, the others can soften the hit to your account.",
      "usuallyGoodWhen": "your holdings are spread across sectors, but spreading out cannot stop losses when the whole market falls.",
      "related": [
        "positionLimit",
        "sector",
        "beta",
        "pctOfAccount"
      ]
    },
    {
      "id": "cashAvailable",
      "group": "trading",
      "label": "Cash available to trade",
      "term": "buying power",
      "whatItIs": "The cash in your account that you can use right now to buy shares.",
      "whyItMatters": "Every buy spends this cash, including the fee, and every sell adds cash back minus the fee.",
      "usuallyGoodWhen": "you keep some cash for later chances, but cash sitting unused earns nothing in this game.",
      "related": [
        "accountValue",
        "invested",
        "fee"
      ]
    },
    {
      "id": "tick",
      "group": "game",
      "label": "Price update",
      "term": "market tick",
      "whatItIs": "A tick is one price update; all prices and standings refresh each tick, every 5 to 30 seconds depending on game length.",
      "whyItMatters": "Prices can change between the moment you look and the moment you trade, so the ticket always shows an estimate.",
      "usuallyGoodWhen": "you preview an order right before placing it, but the price can still change if a new tick arrives first.",
      "related": [
        "session",
        "price",
        "marketOrder"
      ]
    },
    {
      "id": "session",
      "group": "game",
      "label": "Game session",
      "term": "trading session",
      "whatItIs": "One of 8 equal parts of the game, like a trading day in a real market.",
      "whyItMatters": "Session change shows how prices and your account moved since the current session began, apart from the whole game.",
      "usuallyGoodWhen": "your account rises across many sessions, but a single session is short and its moves often reverse.",
      "related": [
        "tick",
        "sessionChange",
        "voyageChange"
      ]
    },
    {
      "id": "quality",
      "group": "game",
      "label": "Health score",
      "term": "quality score",
      "whatItIs": "A hidden score the game gives each company, built only from financial numbers that every crew can read.",
      "whyItMatters": "Healthier companies tend to do a bit better over the whole game, but the score stays hidden until the market reveal.",
      "usuallyGoodWhen": "profit, growth, debt and price all look sensible together, but news, luck and hidden surprises still move prices.",
      "related": [
        "researchGrade",
        "researchEdge",
        "news"
      ]
    },
    {
      "id": "news",
      "group": "basics",
      "label": "News reports",
      "term": "dispatches",
      "whatItIs": "Reports about a company or the whole market, such as profit reports, deals, storms or rule changes, shown in Dispatches.",
      "whyItMatters": "News can move a price quickly, up or down, because it changes what the business is likely to earn.",
      "usuallyGoodWhen": "the news points to lasting changes in the business, but the price jumps the moment news comes out.",
      "related": [
        "sessionChange",
        "volume",
        "analystRating"
      ]
    },
    {
      "id": "researchEdge",
      "group": "game",
      "label": "How much health matters",
      "term": "research edge",
      "whatItIs": "A host setting for how strongly a company's financial health tilts its price over the whole game: Low, Normal or High.",
      "whyItMatters": "On High, careful research pays off more often; on Low, luck plays a bigger part in the results.",
      "usuallyGoodWhen": "you research carefully on any setting, but news and luck can still beat research, most of all on Low.",
      "related": [
        "quality",
        "news",
        "diversification"
      ]
    },
    {
      "id": "ticker",
      "group": "basics",
      "label": "Company symbol",
      "term": "ticker symbol",
      "whatItIs": "A short code of 4 letters that stands for a company, such as KRKN for Kraken Shipping Lines.",
      "whyItMatters": "Symbols are how you search for a company and how it appears in tables, orders and news.",
      "usuallyGoodWhen": "you double-check the symbol before placing an order, but similar symbols are easy to mix up.",
      "related": [
        "stock",
        "marketOrder"
      ]
    },
    {
      "id": "voyageChange",
      "group": "basics",
      "label": "Change since the game began",
      "term": "total change",
      "whatItIs": "How much a price has moved since the first tick of this game, as a percent.",
      "whyItMatters": "It shows the long-run move, which says more about the business than a single session does.",
      "usuallyGoodWhen": "the rise is steady over many sessions, but one news jump can explain most of a big total change.",
      "related": [
        "sessionChange",
        "voyageRange",
        "totalGain"
      ]
    },
    {
      "id": "sharesOutstanding",
      "group": "basics",
      "label": "Shares that exist",
      "term": "shares outstanding",
      "whatItIs": "The total number of shares a company has created, owned by all its investors together.",
      "whyItMatters": "Share count turns company-wide numbers into per-share numbers, like profit per share, and times the price gives company size.",
      "usuallyGoodWhen": "the count stays steady, but comparing share prices across companies means little because share counts differ.",
      "related": [
        "marketCap",
        "eps",
        "float",
        "priceImpact"
      ]
    },
    {
      "id": "float",
      "group": "basics",
      "label": "Shares available to trade",
      "term": "public float",
      "whatItIs": "The shares that ordinary investors can trade, leaving out shares held by insiders like founders and leaders.",
      "whyItMatters": "It shows how much of the company is really out in the market, beyond shares that rarely change hands.",
      "usuallyGoodWhen": "most shares are in the float, but here your order's price nudge depends on total shares, not float.",
      "related": [
        "sharesOutstanding",
        "volume"
      ]
    },
    {
      "id": "week52Range",
      "group": "basics",
      "label": "Past-year high and low",
      "term": "52-week range",
      "whatItIs": "The highest and lowest prices of the stock during the year before this game began.",
      "whyItMatters": "It shows how widely the price swung in the past, a rough guide to how much it can move.",
      "usuallyGoodWhen": "the price has swung less than similar companies, but past swings do not predict where the price goes next.",
      "related": [
        "voyageRange",
        "beta"
      ]
    },
    {
      "id": "sessionRange",
      "group": "basics",
      "label": "Session high and low",
      "term": "session range",
      "whatItIs": "The highest and lowest prices during the current session.",
      "whyItMatters": "A wide range means the price has been jumping around, often because of news.",
      "usuallyGoodWhen": "the range is calm and the business is steady, but a calm session can turn quickly when news arrives.",
      "related": [
        "session",
        "sessionChange",
        "voyageRange"
      ]
    },
    {
      "id": "costOfRevenue",
      "group": "profit",
      "label": "Direct costs",
      "term": "cost of revenue",
      "whatItIs": "What the company spent to make or deliver the things it sold, such as materials, fuel and pay for those workers.",
      "whyItMatters": "Sales minus these costs gives gross profit, the money left to pay every other cost.",
      "usuallyGoodWhen": "these costs grow more slowly than sales, but cutting them too far can hurt quality and future sales.",
      "related": [
        "grossProfit",
        "grossMargin",
        "revenue"
      ]
    },
    {
      "id": "grossProfit",
      "group": "profit",
      "label": "Profit after direct costs",
      "term": "gross profit",
      "whatItIs": "Sales minus direct costs, before paying for things like offices, marketing, interest and taxes.",
      "whyItMatters": "It is the money available to cover all other costs and still leave a profit.",
      "usuallyGoodWhen": "it grows along with sales, but large other costs can still turn it into a loss.",
      "related": [
        "costOfRevenue",
        "grossMargin",
        "operatingIncome"
      ]
    },
    {
      "id": "operatingIncome",
      "group": "profit",
      "label": "Profit from operations",
      "term": "operating income",
      "whatItIs": "Profit from the main business after direct costs and everyday running costs, before interest and taxes.",
      "whyItMatters": "It shows whether the main business makes money on its own, apart from loans and taxes.",
      "usuallyGoodWhen": "it is positive and rising, but heavy interest payments can still leave little final profit.",
      "related": [
        "operatingMargin",
        "grossProfit",
        "netIncome",
        "ebitda"
      ]
    },
    {
      "id": "accountValue",
      "group": "trading",
      "label": "Account value",
      "term": "total account value",
      "whatItIs": "Your cash plus the current value of all the shares you own.",
      "whyItMatters": "Standings rank crews by account value, and the highest value when the game ends wins.",
      "usuallyGoodWhen": "it rises over many sessions, but it moves with every tick, so a high reading can slip away.",
      "related": [
        "cashAvailable",
        "invested",
        "totalGain",
        "startingCash"
      ]
    },
    {
      "id": "invested",
      "group": "trading",
      "label": "Money invested",
      "term": "market value of holdings",
      "whatItIs": "The current value of all the shares you own, at the latest prices.",
      "whyItMatters": "This is the part of your account that goes up and down with stock prices.",
      "usuallyGoodWhen": "it is spread across several companies, but having more invested also means bigger swings in your account.",
      "related": [
        "accountValue",
        "cashAvailable",
        "diversification"
      ]
    },
    {
      "id": "pctOfAccount",
      "group": "trading",
      "label": "Share of account",
      "term": "% of account",
      "whatItIs": "How much of your total account value one holding, or your cash, makes up, as a percent.",
      "whyItMatters": "A big share means that company's price moves have a big effect on your whole account.",
      "usuallyGoodWhen": "no single holding takes up too much, but small holdings can still add up if they all move together.",
      "related": [
        "positionLimit",
        "diversification",
        "accountValue"
      ]
    },
    {
      "id": "feesPaid",
      "group": "trading",
      "label": "Fees paid",
      "term": "commissions paid",
      "whatItIs": "The total of all the trading fees your crew has paid this game.",
      "whyItMatters": "Fees come straight out of your account value, win or lose.",
      "usuallyGoodWhen": "fees stay small next to your gains, but many small trades can add up to a large total.",
      "related": [
        "fee",
        "totalGain"
      ]
    },
    {
      "id": "intervalLimit",
      "group": "trading",
      "label": "Most shares per price update",
      "term": "interval limit",
      "whatItIs": "The most shares of one company your crew can trade between two price updates.",
      "whyItMatters": "It stops giant orders from swinging a price all at once, and the ticket shows the number for each company.",
      "usuallyGoodWhen": "your order fits within the limit, but each order still pays a fee and a small price nudge.",
      "related": [
        "priceImpact",
        "tick",
        "positionLimit"
      ]
    },
    {
      "id": "startingCash",
      "group": "game",
      "label": "Starting cash",
      "term": "starting capital",
      "whatItIs": "The cash every crew gets when the game begins, set by the host.",
      "whyItMatters": "Every crew starts equal, so your total gain compares directly with every other crew's.",
      "usuallyGoodWhen": "your account value stays above it, but a lead early in the game can vanish before the end.",
      "related": [
        "accountValue",
        "totalGain",
        "cashAvailable"
      ]
    },
    {
      "id": "researchGrade",
      "group": "game",
      "label": "Research grade",
      "term": "research grade",
      "whatItIs": "A letter from A to F, shown when the game ends, for how healthy the companies you held were over the whole game.",
      "whyItMatters": "It shows how well your picks matched company health, separate from the luck in your final rank.",
      "usuallyGoodWhen": "you held mostly healthy companies for most of the game, but a high grade does not promise a high rank.",
      "related": [
        "quality",
        "diversification",
        "accountValue"
      ]
    },
    {
      "id": "breadth",
      "group": "basics",
      "label": "Rising vs. falling stocks",
      "term": "market breadth",
      "whatItIs": "How many companies are up, down or unchanged this session.",
      "whyItMatters": "It shows whether a market move is broad, lifting most companies, or narrow, led by just a few.",
      "usuallyGoodWhen": "most companies are rising together, but broad moves can reverse just as broadly.",
      "related": [
        "index",
        "sessionChange",
        "sector"
      ]
    }
  ],
  "news": [
    {
      "type": "earnings",
      "badge": "Earnings",
      "bullish": "Earnings beat forecasts: the company made more profit than expected in its latest report.",
      "bearish": "Earnings missed forecasts: the company made less profit than expected in its latest report."
    },
    {
      "type": "merger",
      "badge": "Merger",
      "bullish": "Merger deal: the company agreed to combine with or buy another business, which could bring more customers, sales or savings.",
      "bearish": "Merger trouble: a planned deal fell apart or now looks too costly, so the hoped-for sales and savings may not come."
    },
    {
      "type": "discovery",
      "badge": "Discovery",
      "bullish": "New discovery: the company found something valuable, such as a new resource or trade route, that could add to future sales.",
      "bearish": "Discovery letdown: something the company was counting on turned out smaller or less valuable than hoped, so future sales may be lower."
    },
    {
      "type": "management",
      "badge": "Leadership",
      "bullish": "Leadership win: the company gained a strong leader or a clearer plan, which could help it run better.",
      "bearish": "Leadership trouble: a key leader left or made a costly mistake, which could make the company harder to run well."
    },
    {
      "type": "regulatory",
      "badge": "Rules",
      "bullish": "Rule change in its favor: officials approved a request or eased a rule, which could lower costs or open new business.",
      "bearish": "Trouble with officials: the company was fined or hit by a stricter rule, which adds costs or limits what it can do."
    },
    {
      "type": "scandal",
      "badge": "Scandal",
      "bullish": "Scandal cleared: the company was found not at fault, which removes a worry about fines or lost customers.",
      "bearish": "Scandal: wrongdoing came to light, which can bring fines, lost customers and damage to the company's name."
    },
    {
      "type": "storm",
      "badge": "Storm",
      "bullish": "Storm recovery: the company came through bad weather better than feared, so less business was lost.",
      "bearish": "Storm damage: bad weather hurt ships, cargo or buildings, which means repair costs and lost sales for a while."
    },
    {
      "type": "macro",
      "badge": "Whole market",
      "bullish": "Market-wide boost: a change such as lower trade taxes helps many companies at once, especially those that swing more with the market.",
      "bearish": "Market-wide setback: a change such as higher trade taxes hurts many companies at once, especially those that swing more with the market."
    }
  ],
  "newsExtra": {
    "whatThisMeans": "What this means",
    "sentiment": {
      "bullish": {
        "label": "Good news for the business (bullish)",
        "short": "Good news"
      },
      "bearish": {
        "label": "Bad news for the business (bearish)",
        "short": "Bad news"
      }
    },
    "sinceReport": "{pct} since the news",
    "sinceReportHelp": "How much the price has moved since this news came out.",
    "companyCount": "{n} companies",
    "marketWide": "Whole market",
    "marketWideHere": "Whole market, including {ticker}",
    "sourceHost": "Posted by the host",
    "filters": {
      "all": "All",
      "holdings": "My holdings",
      "watchlist": "Watchlist"
    },
    "tradeLink": "Trade {ticker}",
    "readMore": "Read more",
    "readLess": "Show less",
    "flavor": "Word from the harbor."
  },
  "explain": [
    {
      "id": "marketCap",
      "label": "Company size (market cap)",
      "valueFormat": "moneyCompact",
      "sentence": "All of its shares together are worth {money} at the current price.",
      "money": "moneyCompact",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 20360000000,
        "valueText": "Ð20.36B",
        "sentence": "All of its shares together are worth Ð20.36B at the current price.",
        "averageText": "Rest of Shipping & Salvage: Ð9.84B"
      },
      "nullExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not available for this company."
      }
    },
    {
      "id": "revenue",
      "label": "Sales (revenue)",
      "valueFormat": "moneyCompact",
      "sentence": "It brought in {money} in sales last year.",
      "money": "moneyCompact",
      "compareNote": "Bigger companies usually have bigger sales, so also compare sales growth, which works at any size.",
      "whenZero": "It had no sales last year.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 8140000000,
        "valueText": "Ð8.14B",
        "sentence": "It brought in Ð8.14B in sales last year.",
        "averageText": "Rest of Shipping & Salvage: Ð5.20B"
      },
      "zeroExample": {
        "value": 0,
        "valueText": "Ð0.00",
        "sentence": "It had no sales last year."
      }
    },
    {
      "id": "netIncome",
      "label": "Profit (net income)",
      "valueFormat": "moneyCompact",
      "sentence": "It made {money} of profit last year after paying every cost.",
      "money": "moneyCompact",
      "compareNote": "Bigger companies usually make bigger profits, so also compare profit margin, which works at any size.",
      "whenZero": "It broke even last year: no profit and no loss.",
      "whenNegative": "It lost {money} last year after paying every cost.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 1140000000,
        "valueText": "Ð1.14B",
        "sentence": "It made Ð1.14B of profit last year after paying every cost.",
        "averageText": "Rest of Shipping & Salvage: Ð0.52B"
      },
      "lossExample": {
        "value": -210000000,
        "valueText": "−Ð0.21B",
        "sentence": "It lost Ð0.21B last year after paying every cost."
      }
    },
    {
      "id": "netMargin",
      "label": "Profit margin (net margin)",
      "valueFormat": "pct1",
      "sentence": "It keeps {money} of profit from every {symbol}100 of sales.",
      "money": "per100",
      "whenZero": "It broke even: no profit left from its sales.",
      "whenNegative": "It loses {money} for every {symbol}100 of sales.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 0.14,
        "valueText": "14.0%",
        "sentence": "It keeps Ð14 of profit from every Ð100 of sales.",
        "averageText": "Rest of Shipping & Salvage: 10.0%"
      },
      "lossExample": {
        "value": -0.035,
        "valueText": "−3.5%",
        "sentence": "It loses Ð3.50 for every Ð100 of sales."
      }
    },
    {
      "id": "grossMargin",
      "label": "Sales kept after direct costs (gross margin)",
      "valueFormat": "pct1",
      "sentence": "After paying for what it sells, it keeps {money} of every {symbol}100 of sales.",
      "money": "per100",
      "whenNegative": "What it sells costs more than it brings in: it loses {money} of every {symbol}100 before other costs.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 0.378,
        "valueText": "37.8%",
        "sentence": "After paying for what it sells, it keeps Ð37.80 of every Ð100 of sales.",
        "averageText": "Rest of Shipping & Salvage: 31.0%"
      },
      "lossExample": {
        "value": -0.05,
        "valueText": "−5.0%",
        "sentence": "What it sells costs more than it brings in: it loses Ð5 of every Ð100 before other costs."
      }
    },
    {
      "id": "revenueGrowth",
      "label": "Sales growth (revenue growth)",
      "valueFormat": "pct1",
      "sentence": "Sales grew about {pct} a year over the last 3 years.",
      "pct": "pctWhole",
      "flatBelow": 0.005,
      "whenFlat": "Sales stayed about the same over the last 3 years.",
      "whenNegative": "Sales shrank about {pct} a year over the last 3 years.",
      "whenNull": "Not enough history to measure sales growth.",
      "example": {
        "value": 0.0719,
        "valueText": "7.2%",
        "sentence": "Sales grew about 7% a year over the last 3 years.",
        "averageText": "Rest of Shipping & Salvage: 4.9%"
      },
      "lossExample": {
        "value": -0.042,
        "valueText": "−4.2%",
        "sentence": "Sales shrank about 4% a year over the last 3 years."
      }
    },
    {
      "id": "eps",
      "label": "Profit per share (EPS)",
      "valueFormat": "money2",
      "sentence": "It made {money} of profit for each share last year.",
      "money": "money2",
      "compareNote": "Profit per share depends on how many shares a company has, so the comparison means little; compare its change over the years instead.",
      "whenZero": "It broke even last year: no profit for each share.",
      "whenNegative": "It lost {money} for each share last year.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 4.73,
        "valueText": "Ð4.73",
        "sentence": "It made Ð4.73 of profit for each share last year.",
        "averageText": "Rest of Shipping & Salvage: Ð2.60"
      },
      "lossExample": {
        "value": -1.2,
        "valueText": "−Ð1.20",
        "sentence": "It lost Ð1.20 for each share last year."
      }
    },
    {
      "id": "peRatio",
      "label": "Price vs. profit (P/E)",
      "valueFormat": "ratio1",
      "sentence": "You pay {money} for every {symbol}1 of yearly profit.",
      "money": "ratioMoney",
      "whenNull": "Not meaningful because the company is losing money.",
      "nullWhen": "netIncome ≤ 0",
      "example": {
        "value": 17.8,
        "valueText": "17.8",
        "sentence": "You pay Ð17.80 for every Ð1 of yearly profit.",
        "averageText": "Rest of Shipping & Salvage: 22.1"
      },
      "lossExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not meaningful because the company is losing money."
      }
    },
    {
      "id": "forwardPe",
      "label": "Price vs. next year's profit (forward P/E)",
      "valueFormat": "ratio1",
      "sentence": "You pay {money} for every {symbol}1 of profit expected next year.",
      "money": "ratioMoney",
      "whenNull": "Not meaningful because the company is losing money.",
      "nullWhen": "netIncome ≤ 0",
      "example": {
        "value": 15.9,
        "valueText": "15.9",
        "sentence": "You pay Ð15.90 for every Ð1 of profit expected next year.",
        "averageText": "Rest of Shipping & Salvage: 21.3"
      },
      "lossExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not meaningful because the company is losing money."
      }
    },
    {
      "id": "psRatio",
      "label": "Price vs. sales (P/S)",
      "valueFormat": "ratio2",
      "sentence": "You pay {money} for every {symbol}1 of yearly sales.",
      "money": "ratioMoney",
      "whenNull": "Not meaningful because the company had no sales.",
      "nullWhen": "revenue ≤ 0",
      "example": {
        "value": 2.5,
        "valueText": "2.50",
        "sentence": "You pay Ð2.50 for every Ð1 of yearly sales.",
        "averageText": "Rest of Shipping & Salvage: 1.90"
      },
      "nullExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not meaningful because the company had no sales."
      }
    },
    {
      "id": "pbRatio",
      "label": "Price vs. owner equity (P/B)",
      "valueFormat": "ratio2",
      "sentence": "You pay {money} for every {symbol}1 of owner equity.",
      "money": "ratioMoney",
      "whenNull": "Not meaningful because the company owes more than it owns.",
      "nullWhen": "equity ≤ 0",
      "example": {
        "value": 3.25,
        "valueText": "3.25",
        "sentence": "You pay Ð3.25 for every Ð1 of owner equity.",
        "averageText": "Rest of Shipping & Salvage: 2.40"
      },
      "nullExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not meaningful because the company owes more than it owns."
      }
    },
    {
      "id": "evToEbitda",
      "label": "Business price vs. core profit (EV/EBITDA)",
      "valueFormat": "ratio1",
      "sentence": "Counting its debt and subtracting its cash, the whole business is priced at {money} for every {symbol}1 of yearly core profit.",
      "money": "ratioMoney",
      "whenNull": "Not meaningful because its core profit, or its price after counting debt and cash, is zero or below.",
      "nullWhen": "ebitda ≤ 0 or enterprise value ≤ 0 (the generator stores 0 in both cases)",
      "example": {
        "value": 10,
        "valueText": "10.0",
        "sentence": "Counting its debt and subtracting its cash, the whole business is priced at Ð10.00 for every Ð1 of yearly core profit.",
        "averageText": "Rest of Shipping & Salvage: 16.4"
      },
      "lossExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not meaningful because its core profit, or its price after counting debt and cash, is zero or below."
      }
    },
    {
      "id": "dividendYield",
      "label": "Yearly payout to owners (dividend yield)",
      "valueFormat": "pct1",
      "sentence": "It pays owners about {money} a year for every {symbol}100 spent on its shares at the current price. Dividends are not added to your cash in this game.",
      "money": "per100",
      "whenZero": "It does not pay owners a dividend right now.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 0.019,
        "valueText": "1.9%",
        "sentence": "It pays owners about Ð1.90 a year for every Ð100 spent on its shares at the current price. Dividends are not added to your cash in this game.",
        "averageText": "Rest of Shipping & Salvage: 1.2%"
      },
      "zeroExample": {
        "value": 0,
        "valueText": "0.0%",
        "sentence": "It does not pay owners a dividend right now."
      }
    },
    {
      "id": "debtToEquity",
      "label": "Debt vs. owner equity (debt-to-equity)",
      "valueFormat": "ratio2",
      "sentence": "It has {money} of debt for every {symbol}1 of owner equity (what it owns minus what it owes).",
      "money": "ratioMoney",
      "whenZero": "It has no borrowed money.",
      "whenNull": "Not meaningful because the company owes more than it owns.",
      "nullWhen": "equity ≤ 0",
      "example": {
        "value": 0.62,
        "valueText": "0.62",
        "sentence": "It has Ð0.62 of debt for every Ð1 of owner equity (what it owns minus what it owes).",
        "averageText": "Rest of Shipping & Salvage: 0.95"
      },
      "nullExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not meaningful because the company owes more than it owns."
      },
      "zeroExample": {
        "value": 0,
        "valueText": "0.00",
        "sentence": "It has no borrowed money."
      }
    },
    {
      "id": "currentRatio",
      "label": "Short-term bill coverage (current ratio)",
      "valueFormat": "ratio2",
      "sentence": "It has {money} of short-term money for every {symbol}1 of bills due within a year.",
      "money": "ratioMoney",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 1.84,
        "valueText": "1.84",
        "sentence": "It has Ð1.84 of short-term money for every Ð1 of bills due within a year.",
        "averageText": "Rest of Shipping & Salvage: 1.35"
      },
      "nullExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not available for this company."
      }
    },
    {
      "id": "freeCashFlow",
      "label": "Cash left after investing (free cash flow)",
      "valueFormat": "moneyCompact",
      "sentence": "After running and investing in the business, it had {money} of cash left last year.",
      "money": "moneyCompact",
      "compareNote": "Bigger companies usually have more cash left over, so also compare it with the company's own profit.",
      "whenZero": "After running and investing in the business, it had no cash left over last year.",
      "whenNegative": "It spent {money} more cash than it brought in last year, after investing in the business.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 960000000,
        "valueText": "Ð0.96B",
        "sentence": "After running and investing in the business, it had Ð0.96B of cash left last year.",
        "averageText": "Rest of Shipping & Salvage: Ð0.38B"
      },
      "lossExample": {
        "value": -150000000,
        "valueText": "−Ð0.15B",
        "sentence": "It spent Ð0.15B more cash than it brought in last year, after investing in the business."
      }
    },
    {
      "id": "roe",
      "label": "Return on owner equity (ROE)",
      "valueFormat": "pct1",
      "sentence": "It earned {money} of profit for every {symbol}100 of owner equity.",
      "money": "per100",
      "whenNegative": "It lost {money} for every {symbol}100 of owner equity.",
      "whenNull": "Not meaningful because the company owes more than it owns.",
      "nullWhen": "equity ≤ 0",
      "example": {
        "value": 0.182,
        "valueText": "18.2%",
        "sentence": "It earned Ð18.20 of profit for every Ð100 of owner equity.",
        "averageText": "Rest of Shipping & Salvage: 11.6%"
      },
      "lossExample": {
        "value": -0.06,
        "valueText": "−6.0%",
        "sentence": "It lost Ð6 for every Ð100 of owner equity."
      }
    },
    {
      "id": "roa",
      "label": "Profit from what it owns (ROA)",
      "valueFormat": "pct1",
      "sentence": "It earned {money} of profit for every {symbol}100 of things it owns.",
      "money": "per100",
      "whenNegative": "It lost {money} for every {symbol}100 of things it owns.",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 0.089,
        "valueText": "8.9%",
        "sentence": "It earned Ð8.90 of profit for every Ð100 of things it owns.",
        "averageText": "Rest of Shipping & Salvage: 5.4%"
      },
      "lossExample": {
        "value": -0.025,
        "valueText": "−2.5%",
        "sentence": "It lost Ð2.50 for every Ð100 of things it owns."
      }
    },
    {
      "id": "beta",
      "label": "Swings vs. the market (beta)",
      "valueFormat": "ratio2",
      "sentence": "When the whole market moves 10%, this stock tends to move about {pct} the same way.",
      "pct": "betaPct",
      "whenNull": "Not available for this company.",
      "example": {
        "value": 1.12,
        "valueText": "1.12",
        "sentence": "When the whole market moves 10%, this stock tends to move about 11% the same way.",
        "averageText": "Rest of Shipping & Salvage: 1.10"
      },
      "nullExample": {
        "value": null,
        "valueText": "—",
        "sentence": "Not available for this company."
      }
    }
  ],
  "explainExtra": {
    "averageLine": {
      "sector": "Rest of {sector}: {avg}",
      "market": "Rest of the market: {avg}",
      "missingAvg": "—",
      "formatRule": "Format {avg} with the metric's valueFormat and {sector} with the company's sector. The company you are reading is never counted in it.",
      "marketNote": "No other company in this sector has this number, so the comparison uses every other company in the market.",
      "whatAverageMeans": "It is the middle value of the other companies in the sector, so there is always a number to compare this one against.",
      "unitsNote": "B means billion, M means million and K means thousand. Ð8.14B is Ð8,140,000,000.",
      "examples": [
        "Rest of Shipping & Salvage: 22.1",
        "Rest of Shipping & Salvage: 10.0%",
        "Rest of Shipping & Salvage: Ð9.84B",
        "Rest of the market: 21.4"
      ]
    },
    "statGrid": {
      "sector": "Rest of sector {avg}",
      "market": "Rest of market {avg}",
      "tapHint": "Tap any stat to see what it means.",
      "formatRule": "Same {avg} formatting and same sector-or-market choice as averageLine, shortened for the caption under a value. The sector name does not fit here.",
      "groups": {
        "price": {
          "label": "Price",
          "note": "Where the price has been, and how much of it changes hands."
        },
        "value": {
          "label": "Value",
          "note": "What you pay for each Ð1 the company earns."
        },
        "size": {
          "label": "Size",
          "note": "How many shares exist, and how many can be traded."
        },
        "health": {
          "label": "Health",
          "note": "How rough the ride has been so far."
        },
        "payouts": {
          "label": "Payouts",
          "note": "What the company hands back to its owners."
        }
      },
      "examples": [
        "Rest of sector 22.1",
        "Rest of sector 10.0%",
        "Rest of market Ð9.84B"
      ]
    },
    "analystCard": {
      "title": "Analyst view",
      "summaryAbove": "Analyst view: {rating}. Their price target of {target} is {pct} above the current price.",
      "summaryBelow": "Analyst view: {rating}. Their price target of {target} is {pct} below the current price.",
      "summaryNone": "No analyst view for this company.",
      "caution": "Analysts in this game are often wrong, and their price targets tend to run high.",
      "example": "Analyst view: Buy. Their price target of Ð96.00 is 14.1% above the current price."
    },
    "statementSummaries": {
      "note": "{firstYear} and {lastYear} are the 4-digit years of the oldest and newest history periods (FY2022 → 2022).",
      "salesUp": "Sales grew from {first} in {firstYear} to {last} in {lastYear}.",
      "salesDown": "Sales fell from {first} in {firstYear} to {last} in {lastYear}.",
      "salesFlat": "Sales stayed about the same from {firstYear} to {lastYear}, near {last}.",
      "profitUp": "Profit grew too, from {first} to {last}.",
      "profitUpSalesDown": "Profit still grew, from {first} to {last}.",
      "profitDown": "Profit fell, from {first} to {last}.",
      "profitFlat": "Profit stayed about the same, near {last}.",
      "lossYears": "The company lost money in {n} of the 4 years shown.",
      "balance": "It has {debtMoney} of debt for every {symbol}1 of owner equity (what it owns minus what it owes).",
      "cashFlow": "After running and investing in the business, it had {fcf} of cash left last year.",
      "flatBelow": 0.03,
      "example": "Sales grew from Ð6.61B in 2022 to Ð8.14B in 2025. Profit grew too, from Ð0.94B to Ð1.14B."
    },
    "research": {
      "helper": "New to this? Start with profit margin, sales growth and debt, then compare price vs. profit (P/E) with similar companies.",
      "fiveQuestionsPanel": "Read this company in 5 questions",
      "fiveQuestionsNote": "Each answer is one clue, not the whole story.",
      "more": "More",
      "flavor": "Chart every company before you commit your doubloons.",
      "views": {
        "basics": {
          "label": "Basics",
          "help": "The key numbers for a first look."
        },
        "valuation": {
          "label": "Valuation",
          "help": "How the price compares with profit, sales and owner equity."
        },
        "health": {
          "label": "Financial health",
          "help": "Debt, bills due soon and cash."
        },
        "analysts": {
          "label": "Analysts",
          "help": "What the game's analysts think, and their price targets."
        }
      }
    }
  },
  "formats": {
    "money2": "Symbol, thousands separators, 2 decimals, true minus: 4.73 → Ð4.73; −1.2 → −Ð1.20",
    "moneyCompact": "Symbol, 2 decimals and a unit, true minus. B from Ð100 million (0.96e9 → Ð0.96B; 20357040000 → Ð20.36B), M from Ð100 thousand, K from Ð1,000, money2 below Ð1,000",
    "per100": "Absolute fraction × 100 as money; drop .00 when whole: 0.14 → Ð14; 0.182 → Ð18.20; 0.378 → Ð37.80; 0.019 → Ð1.90",
    "ratioMoney": "Absolute ratio as money with 2 decimals: 17.8 → Ð17.80; 0.62 → Ð0.62",
    "pct1": "Fraction × 100, 1 decimal, % sign, true minus: 0.14 → 14.0%; −0.031 → −3.1%",
    "pctWhole": "Absolute fraction × 100 rounded to a whole percent; 1 decimal when below 1%: 0.0719 → 7%; 0.004 → 0.4%",
    "ratio1": "1 decimal: 17.78 → 17.8",
    "ratio2": "2 decimals: 0.624 → 0.62",
    "betaPct": "Beta × 10 as a whole percent: 1.12 → 11%",
    "nullValueText": "—"
  },
  "exampleCompany": {
    "ticker": "KRKN",
    "name": "Kraken Shipping Lines",
    "sector": "Shipping & Salvage",
    "averageScope": "sector",
    "values": {
      "price": {
        "value": 84.12,
        "source": "brief"
      },
      "sharesOutstanding": {
        "value": 242000000,
        "source": "brief"
      },
      "marketCap": {
        "value": 20360000000,
        "source": "brief"
      },
      "revenueByYear": {
        "value": [
          6610000000,
          7180000000,
          7740000000,
          8140000000
        ],
        "source": "brief"
      },
      "netIncomeByYear": {
        "value": [
          940000000,
          1030000000,
          1090000000,
          1140000000
        ],
        "source": "brief"
      },
      "revenue": {
        "value": 8140000000,
        "source": "brief"
      },
      "netIncome": {
        "value": 1140000000,
        "source": "brief"
      },
      "netMargin": {
        "value": 0.14,
        "source": "brief"
      },
      "revenueGrowth": {
        "value": 0.0719,
        "source": "derived",
        "note": "(8.14 ÷ 6.61) to the power 1/3, minus 1"
      },
      "eps": {
        "value": 4.73,
        "source": "brief",
        "note": "BRIEF rounding: 1.14B ÷ 242.0M is Ð4.71 and 20.36B ÷ 1.14B is 17.9. BRIEF's EPS 4.73 and P/E 17.8 imply net income near Ð1.144B. Keep BRIEF figures on screens; do not assert EPS = netIncome ÷ shares on this set."
      },
      "peRatio": {
        "value": 17.8,
        "source": "brief"
      },
      "forwardPe": {
        "value": 15.9,
        "source": "brief"
      },
      "psRatio": {
        "value": 2.5,
        "source": "derived",
        "note": "20.36B ÷ 8.14B"
      },
      "equity": {
        "value": 6260000000,
        "source": "derived",
        "note": "1.14B ÷ 18.2%"
      },
      "pbRatio": {
        "value": 3.25,
        "source": "derived",
        "note": "20.36B ÷ 6.26B"
      },
      "totalDebt": {
        "value": 3880000000,
        "source": "derived",
        "note": "0.62 × 6.26B"
      },
      "dividendYield": {
        "value": 0.019,
        "source": "brief"
      },
      "payoutRatio": {
        "value": 0.34,
        "source": "brief"
      },
      "roe": {
        "value": 0.182,
        "source": "brief"
      },
      "debtToEquity": {
        "value": 0.62,
        "source": "brief"
      },
      "currentRatio": {
        "value": 1.84,
        "source": "brief"
      },
      "freeCashFlow": {
        "value": 960000000,
        "source": "brief"
      },
      "costOfRevenue": {
        "value": 5060000000,
        "source": "mockup"
      },
      "grossProfit": {
        "value": 3080000000,
        "source": "mockup"
      },
      "operatingIncome": {
        "value": 1600000000,
        "source": "mockup"
      },
      "grossMargin": {
        "value": 0.378,
        "source": "mockup",
        "note": "3.08B ÷ 8.14B"
      },
      "operatingMargin": {
        "value": 0.197,
        "source": "mockup",
        "note": "1.60B ÷ 8.14B"
      },
      "ebitda": {
        "value": 2280000000,
        "source": "mockup"
      },
      "cash": {
        "value": 1420000000,
        "source": "mockup"
      },
      "evToEbitda": {
        "value": 10,
        "source": "mockup",
        "note": "(20.36B + 3.88B − 1.42B) ÷ 2.28B"
      },
      "totalLiabilities": {
        "value": 6540000000,
        "source": "mockup"
      },
      "totalAssets": {
        "value": 12800000000,
        "source": "mockup",
        "note": "6.26B + 6.54B"
      },
      "roa": {
        "value": 0.089,
        "source": "mockup",
        "note": "1.14B ÷ 12.80B"
      },
      "capex": {
        "value": 880000000,
        "source": "mockup"
      },
      "operatingCashFlow": {
        "value": 1840000000,
        "source": "mockup",
        "note": "0.96B + 0.88B"
      },
      "beta": {
        "value": 1.12,
        "source": "illustrative"
      },
      "intervalCap": {
        "value": 1613333,
        "source": "derived",
        "note": "242,000,000 ÷ 150, rounded down"
      },
      "volume": {
        "value": 184200,
        "source": "brief"
      },
      "analystRating": {
        "value": "Buy",
        "source": "brief"
      },
      "priceTarget": {
        "value": 96,
        "source": "brief"
      }
    },
    "sectorAverages": {
      "marketCap": 9840000000,
      "revenue": 5200000000,
      "netIncome": 520000000,
      "netMargin": 0.1,
      "grossMargin": 0.31,
      "revenueGrowth": 0.049,
      "eps": 2.6,
      "peRatio": 22.1,
      "forwardPe": 21.3,
      "psRatio": 1.9,
      "pbRatio": 2.4,
      "evToEbitda": 16.4,
      "dividendYield": 0.012,
      "debtToEquity": 0.95,
      "currentRatio": 1.35,
      "freeCashFlow": 380000000,
      "roe": 0.116,
      "roa": 0.054,
      "beta": 1.1
    }
  }
};
