/**
 * Host console words: COPY.md §11 host-settings and §11.1 host-errors verbatim, COPY §12 host empty states,
 * and the phone-only host strings of MOBILE §7.17–§7.18. Placeholders are filled with shell `fill()`.
 */

export const HOST_SETTINGS = {
  panelTitle: 'Game settings',
  lockedNote: 'Locked while the game is running. You can change settings only in the lobby.',
  saved: 'Settings saved.',
  gameLength: {
    label: 'Game length',
    help: 'How long trading lasts. Every game has 8 sessions, and prices update every 5 to 30 seconds depending on length.',
    derived: '{hours}-hour game · updates every {tickSeconds} seconds · {totalTicks} ticks',
    options: {
      3600000: '1 hour',
      7200000: '2 hours',
      14400000: '4 hours',
      28800000: '8 hours',
      43200000: '12 hours',
      86400000: '24 hours',
      172800000: '48 hours',
    } as Record<number, string>,
  },
  startingCash: {
    label: 'Starting cash',
    help: 'The cash each crew gets at the start. New crews and new games use this amount.',
    flavor: "Every crew's starting chest.",
  },
  tradingFee: {
    label: 'Trading fee',
    help: 'Charged on every buy and sell as a percent of the order value. The default is 0.10%.',
    unitNote: 'Entered in basis points: 10 basis points equals 0.10%.',
  },
  researchEdge: {
    label: 'Research edge',
    help: 'How much company health affects prices over the whole game.',
    options: {
      low: { label: 'Low', help: 'More luck. Company health matters less.' },
      normal: { label: 'Normal', help: 'Balanced. Health and luck both matter. This is the default.' },
      high: { label: 'High', help: 'Research pays more. Company health matters more.' },
    },
    caution: 'On every setting, news and luck still move prices.',
  },
  positionLimit: {
    label: 'Position limit',
    help: "Caps how much of a crew's account can go into one company, so one all-in bet can't decide the standings.",
    options: {
      1: { label: 'Off', help: 'No cap. A crew can put its whole account into one company.' },
      0.5: { label: '50%', help: 'Up to half of an account in one company. This is the default.' },
      0.35: { label: '35%', help: 'Up to about a third of an account in one company.' },
      0.25: { label: '25%', help: 'Up to a quarter of an account in one company.' },
    } as Record<number, { label: string; help: string }>,
  },
  currency: { label: 'Currency', help: 'The money name and symbol shown everywhere in the game.' },
  newGame: {
    title: 'Start a new game',
    body: 'Creates a fresh market: the same companies with new financial numbers and news. All trades, holdings and history are cleared, and the game returns to the lobby.',
    confirmTitle: 'Start a new game?',
    confirmPrompt: 'Type NEW GAME to confirm.',
    confirmWord: 'NEW GAME',
    confirmButton: 'Start new game',
    cancel: 'Cancel',
    done: 'New game ready. The game is back in the lobby.',
    flavor: 'Fresh charts drawn.',
  },
  keepCrews: {
    label: 'Keep crews and passwords',
    whenOn: 'Crews keep their names and passwords, and each starts again with {startingCash}.',
    whenOff: 'All crews and their sign-ins are deleted. You will need to add crews again.',
  },
  control: {
    start: {
      title: 'Start the game?',
      body: 'Trading opens for every crew and the clock starts. Settings stay locked until you start a new game.',
      button: 'Start game',
    },
    pause: { title: 'Pause trading?', body: "Crews can't place orders, and the clock stops until you resume.", button: 'Pause' },
    resume: { title: 'Resume trading?', body: 'Orders open again, and the clock continues from where it stopped.', button: 'Resume' },
    end: {
      title: 'End the game now?',
      body: "Trading closes for good, holdings are valued at closing prices, and the market reveal opens. This can't be undone.",
      button: 'End game',
    },
    heartbeat: { ok: 'Engine healthy', warn: 'Engine running slow', bad: 'Engine not responding', idle: 'Engine idle' },
  },
} as const;

export type HostErrorCode = 'exists' | 'bad_name' | 'not_found' | 'busy' | 'bad_request' | 'internal';

export const HOST_ERRORS: Record<HostErrorCode, { title: string; message: string }> = {
  exists: {
    title: 'Name already taken',
    message: 'A crew with this name already exists. Names ignore capitals and punctuation, so pick a clearly different name.',
  },
  bad_name: { title: 'Check the crew name', message: 'Use at least one letter or number. The name admin is kept for the host.' },
  not_found: {
    title: 'Crew not found',
    message: "We couldn't find that crew. It may have been removed. Refresh the crew list and try again.",
  },
  busy: { title: 'New game in progress', message: 'A new game is being prepared. Wait a moment, then try again.' },
  bad_request: { title: 'Check your entry', message: "Something in that request isn't valid. Check the fields and try again." },
  internal: {
    title: 'Something went wrong',
    message: "The server couldn't finish that. Try again. If it keeps failing, ask your developer to check the server logs.",
  },
};

/** COPY §12 host empty states. */
export const HOST_EMPTY = {
  hostCrews: { title: 'No crews yet', body: 'Add a crew to give players a name and password.' },
  hostNews: { title: 'No news scheduled', body: 'Scheduled news appears here after the game starts.' },
} as const;

/** MOBILE §7.17–§7.18 phone-only host strings (COPY-TBD). */
export const HOST_PHONE = {
  pauseTrading: 'Pause trading',
  resumeTrading: 'Resume trading',
  endGame: 'End game…',
  typeEnd: 'Type END to confirm.',
  sessionOf: 'Session {session} of 8',
  quickActions: 'Quick actions',
  fireNews: 'Fire news…',
  findCrew: 'Find a crew…',
  tradeTape: 'Trade tape',
  auditLink: 'Audit',
  more: 'More options',
  editSettings: 'Edit settings',
  newGame: 'New game…',
  gameControl: 'Game control',
  timeLeft: 'Time left',
  crews: {
    search: 'Search crews',
    add: 'Add crew',
    name: 'Crew name',
    password: 'Password',
    show: 'Show password',
    initials: 'Initials',
    startingCash: 'Starting cash',
    create: 'Add crew',
    added: '{crew} added.',
    tradingOff: 'Trading off',
    tradingAllowed: 'Trading allowed',
    resetPassword: 'Reset password…',
    newPassword: 'New password',
    savePassword: 'Save password',
    passwordSaved: 'Password changed for {crew}.',
    passwordHint: 'At least 4 characters.',
    remove: 'Remove crew…',
    removeTitle: 'Remove {crew}? This deletes its login, holdings, history and trades.',
    removeButton: 'Remove crew',
    removed: '{crew} removed.',
    value: 'Account value',
    cash: 'Cash',
    trades: 'Trades',
    rank: 'Rank',
    returnPct: 'Return',
    holdings: 'Holdings',
    noHoldings: 'No holdings yet.',
    shares: '{shares} shares',
    count: '{count} crews',
  },
  market: {
    banner: 'Host only: never project this screen',
    bannerBody: 'Students must not see quality scores during play. Crews see only Last, Session % and Volume.',
    companies: '{count} companies',
    last: 'Last',
    session: 'Session %',
    volume: 'Volume',
    netFlow: 'Net order flow',
    quality: 'Quality score',
    grade: 'Grade',
    fairValue: 'Fair value',
    deviation: 'Price vs fair value',
    meaning: 'What these numbers mean',
  },
  news: {
    scheduled: 'Scheduled',
    fired: 'Fired',
    view: 'Show',
    fireTitle: 'Fire news',
    cancel: 'Cancel',
    companies: 'Companies',
    addCompany: 'Add company',
    removeCompany: 'Remove {ticker}',
    searchCompanies: 'Search companies',
    impactType: 'Impact type',
    direction: 'Direction and size',
    lower: 'Lower by 1%',
    raise: 'Raise by 1%',
    preview: 'Price after the news',
    headline: 'Headline',
    body: 'Body (optional)',
    counter: '{count}/{max}',
    zeroHint: 'Pick a move above or below 0%.',
    notRunning: 'News can be fired only while the game is live or paused.',
    queued: 'News queued for tick {tick}.',
    tick: 'Tick {tick}',
    hostOnly: 'Hidden from crews until it fires',
    noFired: 'No news fired yet',
    noFiredBody: 'Dispatches show here after they reach the crews.',
    source: { scheduled: 'Scheduled', macro: 'Whole market', host: 'Host' },
  },
  tape: {
    title: 'Trade tape',
    filter: 'Filter trades',
    allCrews: 'All crews',
    allCompanies: 'All companies',
    byCrew: 'Crew',
    byCompany: 'Company',
    bought: 'Bought',
    sold: 'Sold',
    empty: 'No trades yet',
    emptyBody: 'Fills from every crew show here as they happen.',
    emptyFiltered: 'No trades for this filter',
    emptyFilteredBody: 'Choose All crews and All companies to see every fill.',
    time: 'Time',
    crew: 'Crew',
    action: 'Action',
    ticker: 'Symbol',
    qty: 'Qty',
    price: 'Fill price',
    fee: 'Fee',
    tick: 'Tick',
    latest: 'Latest {count} fills across all crews',
  },
  audit: {
    title: 'Audit',
    refresh: 'Refresh',
    empty: 'No host actions yet',
    emptyBody: 'Every host change is recorded here.',
    time: 'Time',
    action: 'Action',
    actor: 'By',
    details: 'Details',
  },
  loadError: "Couldn't load this page",
  retry: 'Try again',
  offline: "You're offline",
  offlineBody: 'Check your connection and try again.',
} as const;
